# This is a sample configuration to run a Drupal-instance with Docker-Compose.
# For customization options see: https://docs.docker.com/compose/yml/

web:
  image: samos123/drupal:7.x
  links:
    - db:mysql
  ports:
    - "80:80"
  volumes:
    - /var/www/html/sites
    - /var/www/private
  environment:
    - UPLOAD_LIMIT=20M
    - MEMORY_LIMIT=128M

db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - /var/lib/mysql
